name: GitHubPages

on:
  push:
    branches: gh-actions

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install packages
        run:  npm install

      - name: Build
        run:  npm test

      - name: View environment
        run:  env

      - name: View remote
        run:  git remote -v
