name: GitHubPages

on:
  push:
    branches: gh-actions

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Get commit name
        id: commit_name
        run: echo "::set-env CMMT=`git log -1 --format=%h:\t%s`"

      - name: Check out WWW
        uses: actions/checkout@v2
        with:
          ref: www
          path: www

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install packages
        run:  npm install

      - name: Build
        run:  npm test

      - name: Copy data
        working-directory: www
        run: |
          rm -rf *
          cp -r ../j2gtsp/* .
          git add --all
          git config user.email "none"
          git config user.name "Publisher"
          git commit -m "$CMMT"
          git push
