name: GitHubPages

on:
  push:
    branches: gh-actions

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Check out WWW
        uses: actions/checkout@v2
        with:
          ref: www
          path: www

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install packages
        run:  npm install

      - name: Build
        run:  npm test

      - name: Upload repo
        uses: actions/upload-artifact@v1
        with:
          name: uno
          path: .git

      - name: Upload repo II
        uses: actions/upload-artifact@v1
        with:
          name: uno
          path: www/.git
