name: GitHubPages

on:
  push:
    branches: gh-actions

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Total recall
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check out
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install packages
        run:  npm install

      - name: Build
        run:  npm test

      - name: Upload artifact(s)
        uses: actions/upload-artifact@v1
        with:
          name: www
          path: j2gtsp
